"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 1.10.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '2sp#(p9%@+zj477lom$7nacoc-zm$nk#m=41lu%!&zoel09ek5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    
    'channels',
    'django.contrib.sites',

    'allauth',
    'allauth.account',
    'allauth.socialaccount',

    'classroom',
    'taskapp',
    'chat',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',
    
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'classroom','templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
              
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # 'django.core.context_processors.csrf',
            ],
        },
    },
]

AUTHENTICATION_BACKENDS = (
    
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',
    
)

SITE_ID=1

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'mydb2',
        'USER': 'mydatabaseuser3',
        'PASSWORD':'mypassword',
        'HOST':'127.0.0.1',
        'PORT':'5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Calcutta'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'

LOGIN_REDIRECT_URL='/classroom/profile'
ACCOUNT_LOGOUT_REDIRECT_URL='/classroom/'

#login limit= 5 times
ACCOUNT_LOGIN_ATTEMPTS_TIMEOUT=3

ACCOUNT_EMAIL_REQUIRED=True
ACCOUNT_EMAIL_VERIFICATION="none"



RECAPTCHA_PUBLIC_KEY = '6LdG7UwUAAAAANP-Lhj4V5Nq2HT04AO9c0Q7ARfM'
RECAPTCHA_PRIVATE_KEY = '6LdG7UwUAAAAAPMJMDLGU7HP5pJC9UjM8DZRlSn8'
NOCAPTCHA = True

# ACCOUNT_FORMS = {
#     'signup': 'myproject.forms.CustomSignupForm',
# }

ACCOUNT_SIGNUP_FORM_CLASS = 'classroom.forms.SignupForm'

# ACCOUNT_FORMS = {'signup': 'classroom.forms.MySignupForm'}   ---- Giving error

# redis_host=os.environ.get('REDIS_HOST','localhost')

# CHANNEL_LAYERS={
#     "default":{
#     "BACKEND":"asgi_redis.redisChannelLayer",
#     "CONFIG":{
#     "hosts":[(redis_host,6379)],
#     },
#     "ROUTING":"multichat.routing.channel_routing",
#     },
# }


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

#http%3A%2F%2F127.0.0.1%3A8000%2Faccounts%2Ffacebook%2Flogin%2Fcallback%2F&scope=email
#http://localhost:8000/accounts/facebook/login/callback/&scope=email
#http://localhost:8000/accounts/facebook/login/callback/&scope=email&response_type=code


ASGI_APPLICATION = "mysite.routing.application"
