# Generated by Django 2.0.4 on 2018-04-22 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0007_auto_20180419_2244'),
    ]

    operations = [
        migrations.CreateModel(
            name='userMoreInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField()),
                ('designation', models.CharField(choices=[(1, 'Teacher'), (2, 'Student')], max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
