# Generated by Django 2.0.4 on 2018-04-22 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0008_auto_20180422_1626'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userMoreInfo',
        ),
    ]
