# Generated by Django 2.0.4 on 2018-04-22 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0010_usermoreinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermoreinfo',
            name='user',
        ),
        migrations.DeleteModel(
            name='userMoreInfo',
        ),
    ]
